version: '3'

services: 
    annotation-api:
        image: annotations-api
        ports:
            - "4001:4001"
        depends_on: 
            - redis
            - mongodb
        restart: always
    users-api:
        image: users-api
        ports: 
            - "4004:4002"
        depends_on: 
            - redis
            - db
        restart: always
    redis:
        image: "redis:alpine"
        restart: always
    db:
        image: "postgres:alpine"
        ports: 
            - "5432:5432"
        environment: 
            POSTGRES_PASSWORD: "admin"
            POSTGRES_DB: "annotations-db"
        restart: always
    mongodb:
        image: "mongo:4.2.2"
        ports: 
            - "27017:27017"
        environment: 
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=operator
        restart: "always"

