version: '3'

services: 
    annotation-api:
        image: annotations-api
        ports:
            - "4001:4001"
        depends_on: 
            - redis
            - db
        restart: always
    users-api:
        image: blindern/users-api
        ports: 
            - "4002:4002"
        depends_on: 
            - redis
            - db
        restart: always
    redis:
        image: "redis:alpine"
        restart: always
    db:
        image: "postgres:alpine"
        environment: 
            POSTGRES_PASSWORD: "admin"
            POSTGRES_DB: "annotations-db"
        restart: always

